### ISSUE TITLE
About the minImageNet dataset  

### ISSUE THREAD

**Issue by 123675** [icoz69/DeepEMD#15]
Hello!
  In the evaluation stage of minIageNet datasets, there are 20 types of samples, each of which has 600 samples, which means 12,000 samples. If you use the 5-way 1-shot experimental setting, it means that one task requires 80 images and your epoch has 5000 tasks, which means that 400,000 pictures are used, and you used data amplification? Or is the sample reused in one epoch? thank you for your patience!

**Comment by icoz69** [comment]
I dont quite understand your questions. data augmentation is used for all dataset.
