### ISSUE TITLE
Request for the complete arguments for the eval part.

### ISSUE THREAD

**Issue by songquanpeng** [icoz69/DeepEMD#18]
Hello, first of all thanks for your excellent work!
But when I try to reproduce the results that you provided, what I got is pretty low. 

Here is the complete log for `MiniImageNet DeepEMD-FCN 1-Shot 5-Way`:
```
C:\Users\admin\Anaconda3\envs\tensorflow\python.exe D:/Projects/DeepEMD/eval.py
{'data_dir': 'your/default/dataset/dir',  # it's fine because I make some changes to the fcn\mini_imagenet.py and already hardcode the real path.
 'dataset': 'miniimagenet',
 'deepemd': 'fcn',
 'feature_pyramid': None,
 'gpu': '0', 
 'metric': 'cosine',
 'model_dir': 'D:\\Projects\\DeepEMD\\trained\\deepemd_trained_model\\miniimagenet\\fcn\\max_acc.pth',
 'norm': 'center',
 'num_patch': 9,
 'patch_list': [2, 3],
 'patch_ratio': 2,
 'query': 15,
 'seed': 1,
 'set': 'test',
 'sfc_bs': 4,
 'sfc_lr': 100,
 'sfc_update_step': 100,
 'sfc_wd': 0,
 'shot': 1,
 'solver': 'opencv',
 'temperature': 12.5,
 'test_episode': 5000,
 'way': 5}
manual seed: 1
use gpu: [0]
loading model from : D:\Projects\DeepEMD\trained\deepemd_trained_model\miniimagenet\fcn\max_acc.pth
batch 5000: This episode:49.33  average: 57.1491+0.2795: 100%|██████████| 5000/5000 [38:01<00:00,  2.19it/s]
test Acc 57.1491
Test Acc 57.1491 + 0.2795

Process finished with exit code 0
```

I think if you could publish the complete arguments it will help to resolve this problem.

Thx in advance!

**Comment by icoz69** [comment]
hi. did you change any parts of the code? i have checked the model the running scripts before uploading them, and there are no problems here. Using the default arguments should be OK.

**Comment by songquanpeng** [comment]
Thanks for your reply! I will check my changes again later.

**Comment by Jiawen-huang** [comment]
I noticed that your arguments have not been updated.
'sfc_lr': 100 
I think this argument is unreasonable

**Comment by icoz69** [comment]
@Jiawen-huang ,
hi, as cosine is used to compute the EMD distance between SFC and data embedding, the magnitude of fc weights will not influence the distance. so the lr can be very large for quicker optimization.
