### ISSUE TITLE
the resolution of input image

### ISSUE THREAD

**Issue by Tsingularity** [icoz69/DeepEMD#19]
Hi, thanks a lot for the great work!

But I am a little bit confused about the resolution of the input images and I don't see you explained it explicitly in the original paper. I took a look at your dataloader code and seems like they are taking the original-size image (as large as 300*300) and do randomresizecrop (into 84) during training? please correct me if my understanding is wrong.

If yes, I am quite concerned that the comparison is quite unfair then? Cause according to my knowledge, most numbers on mini-imagenet are using the pre-resized 84 as input (except closer look at few-shot and simpleshot)?

Thanks in advance and looking forward to ur reply!

**Comment by icoz69** [comment]
hello
thanks for your interest in our work.
You are right about the dataloader part. Our project is based on the open-source code of [feat](https://github.com/Sha-Lab/FEAT).
I think this is a standard way for image classification tasks. Although early works in few shot learning/meta learning pre-process data very easily, such as no data augmentation, I think it is better not to ignore the standard operations, such as random crop/scale. Otherwise it is hard to know whether an algorithm really sloves the problem or just simply play the same role as data augmentation.
Anyway, if you would love to test our algorithm with other data pre-processing methods, it is easy to modify based on our project.

**Comment by Tsingularity** [comment]
Thanks a lot for your quick response!

Yes I agree this is a standard way for the normal image recognition task. but when we compare with baselines, we need to ensure that the methods are using the same data-preprocessing (no matter which one, just like what u said, otherwise "it is hard to know whether an algorithm really sloves the problem or just simply play the same role as data augmentation" )? Or at least I think it would be better to indicate in the paper that which method uses what data-preprocessing?

And thanks for pointing out you constructed your code based on FEAT. And I just checked their implementation, I noticed that for the CUB dataset, FEAT mentioned that they are using the bounding-box cropped CUB images instead of the original one. So the CUB number in your papers are also implemented in this way?

Thanks for your answer again!

**Comment by icoz69** [comment]
1.all the analysis experiments we  compared are all using the same data augmentation strategy and training strategy, so you can see the protonet, matching net, closer look, yield higher results than their reported ones, we have indicated this below the table.

2.The CUB dataset we are usign is the same with FEAT's.

**Comment by Tsingularity** [comment]
1. speaking of the numbers in the table. I am confused about several numbers. Since you said your code is based on FEAT's, why the paper doesn't use the proto/FEAT model numbers in the FEAT paper? In that paper, the proto's resnet-12 results are 62.39 and 80.53, and in ur paper, proto's numbers are 60/78. And FEAT's original resnet-12 numbers are 66.78 and 82.05, but in your paper, why the numbers become 62.96/78.02? The other number is Meta-Opt's, I think their implementation only uses pre-resized 84 images instead of original images with severe augmentation. (Please correct me if i am wrong).

2. Except deepEMD, FEAT and hyperbolic embedding, I don't think I see any paper's implementation using the bounding-box cropped images as input. (Again, please correct me if I am wrong). Could you please give me a reference that I can refer to the CUB baseline numbers in your table 3c?

Thanks!

**Comment by icoz69** [comment]
1. FEAT has been updated to arxiv very early. The results you see now is their latest version after CVPR2020 submission, you can check the history of arxiv to find their previous performance. 
2. For the results in Table3C, part of some is based on our implementation, while for the others , we added the citation behind the method name, which you can refer to.
As to the resolution, if you would love to obtain a result with other augmentation strategies, such as raw image size or pre-resized images, you can modify our code very easily, and report this result as you need.
