### ISSUE TITLE
Some questions about the ResNet-12 and the optimizer setting

### ISSUE THREAD

**Issue by Harry-Up** [icoz69/DeepEMD#2]
Hi, thanks for your great work! I have some questions about the structure of ResNet-12 and the optimizer setting. 

Firstly, why are the channels of ResNet-12 set as [64, 160, 320, 640]? Such a setting is common in WideResNet-28*10 rather than ResNet-12, which should be [64, 128, 256, 512]. Especially, in the paper, the Implementation Details section describes the feature map size which is 5\*5\*512. It seems a change after finishing the paper. So, I wonder how much this change has affected the performance?

Meanwhile, the optimizer adopts second-order optimization. It is also not common in the previous works. Although the training process really depends on each work, I wanna try a training from scratch without it.

**Comment by icoz69** [comment]
hello
thanks for the question. the backbone we used is aligned with other works without any special medications, such as [FEAT](https://github.com/Sha-Lab/FEAT/blob/master/model/networks/res12.py). the 512 should be a typo in the paper.  this should not have much influence on the performance of the model. in our experiment after submission, we find that replacing the backbone to deeper ones can further boost the performance.

our network is in a bi-level optimization form but does not compute the second-order gradient as is done in MAML.  we use the QPTH solver which employs implicit function theorem to compute gradients.  you may refer to the two papers below to get more details.
https://arxiv.org/pdf/1703.00443.pdf
https://arxiv.org/pdf/1804.05098.pdf
