### ISSUE TITLE
Configs for training 5-shot models

### ISSUE THREAD

**Issue by LouieYang** [icoz69/DeepEMD#20]
Hello, thanks for your great work first.

I want to reproduce some results on 5-shot tasks but found the training process quite slow compared to 1-shot tasks (e.g. 10-20 seconds/iterations), is it normal? or could you share the training configs for 5-shot tasks.

btw, I also have questions about how you improve your numbers on miniimagenet 5-way 1-shot task from CVPR version (65.91) to arxiv version? any suggestion is appreciated.

Thanks
Yang

**Comment by icoz69** [comment]
Hi Yang
Actually, we don't train a 5-shot model. We directly use the 1-shot model to test.

I don't quite understand your 2nd question. The difference between two versions is DeepEMD-Grid and DeepEMD-Sampling.

**Comment by LouieYang** [comment]
In CVPR version, the results of DeepEMD-FCN for 1-shot tasks on miniimagenet is 65.81 in Table 4(a) while in DeepEMD v2 the results for DeepEMD-FCM becomes 66.50 in Table 6(a). So I wonder where the improvement comes from?

**Comment by icoz69** [comment]
Hi, the improvements come from the pyramid structure. You may check the details in the paper.

**Comment by LouieYang** [comment]
ok, I see the differences

Many thanks.
