### ISSUE TITLE
About GPU utilization during meta-training(meta-val)

### ISSUE THREAD

**Issue by CharleyZhao123** [icoz69/DeepEMD#23]
Hello, first of all, thank you very much for your excellent work！！ When I run meta-training (meta-val), I found a problem, I would like to ask you.
I ran the experiment on 12 GB NVIDIA Titan V GPUs. I found that during meta-training ( meta-val ), the GPU utilization has been fluctuating and at a relatively low level. I don't know if you have found the same problem, or if it was my fault. If you have found this phenomenon as well, is it a bug, or is it inevitable? 
This situation does not exist in the pre-training phase and only exists when meta-training or meta-validation, meta-testing is involved.

Looking forward to your reply. Thank you！！

**Comment by ws1414153477** [comment]
Have you solved the problem？
