### ISSUE TITLE
Experimental results on miniimagenet dataset

### ISSUE THREAD

**Issue by Wang01l** [icoz69/DeepEMD#27]
Hello, thanks for your great work first.
I downloaded the Meta-trained models and tested DeepEMD-FCN with it for 1-shot 5-way task on the miniImageNet dataset, but the result is different from that in the paper. The results of DeepEMD-FCN for 1-shot tasks on miniimagenet is 57.46,  pretty lower than your experimental result. I want to know what caused it.
I am really desperate for the answer.
Thanks in advance for your help.

**Comment by icoz69** [comment]
hello, are you changing any parts of the code?  i have double-checked before uploading. how about downloading the code and run it again?

**Comment by Wang01l** [comment]
Hello, I downloaded the code again and ran it again. But the result is still the same.

**Comment by icoz69** [comment]
how about the dataset?

**Comment by Wang01l** [comment]
Thank you very much for your reply. I use miniimagenet dataset downloaded from other places. Will this have any impact? Has your dataset been processed in advance？Then I'll download your dataset for testing and look at the results.

**Comment by icoz69** [comment]
hi, you may refer to [this issue](https://github.com/icoz69/DeepEMD/issues/19).  might be related.

**Comment by Wang01l** [comment]
Thank you. I'll download the dataset and test it again.
In addition, I have another question. When I train the cub dataset, there will always be such errors. Have you encountered them? How did you solve them?
`RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:110`

**Comment by Wang01l** [comment]
Hello, I've solved that problem. I used the dataset you provided, and the test results are similar to the data you provided. In addition, I have solved the problem of cub dataset. In datautils.py  of dataloder:
```
elif args.dataset == 'cub':
args.num_class = 100
```
The value of num_class needs to be changed to 100.
Finally, can you provide the visualization program in the paper?
I am really desperate for the answer.
Thanks in advance for your help.

**Comment by icoz69** [comment]
hi , thank your pointing our the issue.
for the visualization program, it is not compatible with the released code. You may drop me an email and I can send you the raw code for reference. you may also write one on your own.
After you obtain the flow matrix from opencv or QPTH, you actually get a correspondence matrix. Then you only need to write a script to crop&paste patches based on it. Then you use normalized weights to control the brightness.

**Comment by karayzhou** [comment]
Hello, thanks for your great work first. Could you give more details about 5-shot setting ,such as "max_epoch","val_frequency","val_episode". Thank you
