### ISSUE TITLE
about tiered imagenet dataset

### ISSUE THREAD

**Issue by Tsingularity** [icoz69/DeepEMD#29]
I downloaded the tiered imagenet dataset using the google drive link you provided but found that those images are not actually the same as the [original dataset](https://github.com/renmengye/few-shot-ssl-public), which is usually the one people are using for fair comparison i think.

The original dataset contains images that have been pre-processed into 84\*84, but in your dataset, seems like the images are all in 224\*224. Could you please: 
1. release the details about how to do the data pre-processing?
2. give some reference that any baseline methods are using the same dataset format?

Thanks!

**Comment by icoz69** [comment]
hi, our project is built upon the codes of FEAT, where the input image size is 84 * 84, rather than 224.  all the baselines in our experiment are re-implemented for fair comparision.
