### ISSUE TITLE
CUB dataset is not original one

### ISSUE THREAD

**Issue by XuLuo-ai** [icoz69/DeepEMD#35]
I notice that the CUB dataset you use is the accurately cropped version, not the same as in "Take a closer look at FSL".  Is this somehow unfair?

**Comment by icoz69** [comment]
hi, thanks for the comment. the dataset split of CUB we use follows FEAT, and we have re-implemented many baselines for comparison, such as protonet, matching net, baseline++, etc. 
If you want to use our method on the dataset you are using, it's easy to replace the dataset loader with yours.
