### ISSUE TITLE
Why can't I change the head layer to a protonet?

### ISSUE THREAD

**Issue by smallbox120** [icoz69/DeepEMD#9]
I use the script and the pre-trained model provided by the auther (resnet12), only get 70.5% on 1-shot tiered-imagenet testset, which is at least 4% behind what's reported in the paper. Can other people reproduce the results on tiered?

**Comment by icoz69** [comment]
hello 
your question seems related to [issues 4](https://github.com/icoz69/DeepEMD/issues/4). I pre-train all these models right before open-sourcing the codes, so they are not carefully tuned for each dataset. you may slightly vary the hyper-parameters to obtain better results.
